import { SessionStatus, UNIQUE_VIOLATION } from '@app/common';
import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { CarRef } from './entities/car-ref.entity';
import { SessionRef } from './entities/session-ref.entity';

/**
 * Opens and closes `sessions` rows on behalf of devices.
 *
 * Sessions are device-driven in this design: the car publishes `start` and
 * `stop`, and this is what turns those into rows. The REST API can still create
 * sessions (those have a null `deviceSessionId`), but a driver at a track never
 * has to.
 */
@Injectable()
export class IngestSessionsService {
  private readonly logger = new Logger(IngestSessionsService.name);

  constructor(
    @InjectRepository(CarRef)
    private readonly cars: Repository<CarRef>,
    @InjectRepository(SessionRef)
    private readonly sessions: Repository<SessionRef>,
  ) {}

  findCarByDeviceId(deviceId: string): Promise<CarRef | null> {
    return this.cars.findOne({ where: { deviceId } });
  }

  findByDeviceSessionId(sid: string): Promise<SessionRef | null> {
    return this.sessions.findOne({ where: { deviceSessionId: sid } });
  }

  /**
   * The session for this `sid`, creating it if this is the first we have heard
   * of it. Returns the existing row unchanged when there is one, so a duplicate
   * `start` — or a backlog replayed hours later — resolves back to the original
   * session instead of opening a second.
   *
   * Null when the `sid` already belongs to a **different** car. A `sid` is
   * generated by a device and is therefore attacker-controlled in the only
   * sense that matters here: the broker ACL proves which car published a frame,
   * but nothing stops that car putting another car's `sid` in the body — a
   * cloned SD image or a re-flashed unit reusing a baked-in UUID does it by
   * accident. Without this check, car B's GPS trace would be written into car
   * A's session and become readable by A's team. The authenticated deviceId
   * wins over the payload, always.
   *
   * The car's owner becomes the driver of record. The device cannot know who is
   * behind the wheel, and the owner is the only person the platform can
   * attribute a run to without guessing; a manager can reassign it afterwards.
   */
  async openSession(
    car: CarRef,
    sid: string,
    monoMs: number,
    track?: string,
  ): Promise<SessionRef | null> {
    const existing = await this.findByDeviceSessionId(sid);
    if (existing) {
      return existing.carId === car.id ? existing : null;
    }

    const session = this.sessions.create({
      carId: car.id,
      driverId: car.ownerId,
      track: track || 'unknown',
      startedAt: new Date(),
      status: SessionStatus.LIVE,
      deviceSessionId: sid,
      deviceMonoStartMs: monoMs,
    });

    try {
      return await this.sessions.save(session);
    } catch (error) {
      // Another frame for the same run got here first. The unique index on
      // deviceSessionId is what makes that a re-read rather than a second row.
      if ((error as { code?: string })?.code === UNIQUE_VIOLATION) {
        const raced = await this.findByDeviceSessionId(sid);
        // Same ownership rule as above — the race could have been lost to a
        // different car claiming this sid, not just to another of our frames.
        return raced?.carId === car.id ? raced : null;
      }
      throw error;
    }
  }

  /**
   * Closes the run. Deliberately not `findOneAndUpdate`-strict: a `stop` for a
   * session that is already closed is a retransmit, not an error.
   *
   * Scoped by `carId` as well as `sid` for the same reason `openSession` is:
   * otherwise any car could end another team's session in progress just by
   * publishing a stop carrying their `sid`.
   */
  async closeSession(carId: string, sid: string): Promise<void> {
    const result = await this.sessions.update(
      { deviceSessionId: sid, carId, status: SessionStatus.LIVE },
      { status: SessionStatus.COMPLETED, endedAt: new Date() },
    );

    if (!result.affected) {
      this.logger.debug('Stop event for a session that was not live');
    }
  }
}
